title: Aaron Mercado # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  "Most of the chance improvements in human motions that eliminate unnecessary 
  movement and reduce fatigue have been hit upon, Gilbreth thinks, by men who were 
  lazyâ€”so lazy that every needless step counted." - Frank B. Gilbreth Sr. (1920)
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
